name: Update version.json

on:
  push:
    branches: [ main ]
    paths-ignore:
      - version.json

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version.json
        run: |
          HASH=$(git rev-parse --short HEAD)
          MESSAGE=$(git log -1 --pretty=%B | tr '\n' ' ')

          echo "{ \"version\": \"$HASH\", \"message\": \"$MESSAGE\" }" > version.json

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add version.json
          git commit -m "Update version.json [$HASH]" || exit 0
          git push
